name: Docker Build

on:
  push:
    branches:
      - master
      - development
      - web-dev

jobs:
  build-windows:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 5.6.2
          arguments: shadowJar
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch
      - name: Get commit hash
        shell: bash
        run: echo "##[set-output name=hash;]$(echo $(git rev-parse --short "$GITHUB_SHA") | cut -c1-6)"
        id: get_hash
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rubbaboy/hs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "${{ steps.get_branch.outputs.branch }}-latest,${{ steps.get_branch.outputs.branch }}-${{ steps.get_hash.outputs.hash }}"
      - name: Repository published
        run: echo "docker pull rubbaboy/hs:${{ steps.get_branch.outputs.branch }}-${{ steps.get_hash.outputs.hash }}"
      - name: Create docker shield
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: hs
          LABEL: docker
          STATUS: "hs:${{ steps.get_branch.outputs.branch }}-${{ steps.get_hash.outputs.hash }}"
          COLOR: 0576B7
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
