name: Docker Build

on:
  push:
    branches:
      - master
      - development
      - web-dev

jobs:
  build-windows:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 5.6.2
          arguments: shadowJar
      - run: "${GITHUB_REF##*/}"
      - run: ${GITHUB_REF##*/}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rubbaboy/hs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
          dockerfile: Dockerfile
          tags: "${GITHUB_REF##*/}"
